# Generated by Django 5.2.11 on 2026-02-23 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=100)),
                ('plan_name', models.CharField(max_length=200)),
                ('last_renewed_date', models.DateField()),
                ('billing_cycle', models.CharField(max_length=50)),
                ('auto_renew', models.BooleanField()),
                ('trial_end', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('status', models.CharField(default='active', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supportAI.customer')),
            ],
        ),
    ]
